openapi: 3.1.0

info:
  version: "0.1"
  title: Cutting edge localization Service API
  description: |
    Enter here a whole verbose description of the API in markdown format
    # Introduction
    Lorem ipsume
    # Some Definitions
    Lorem ipsume
  contact:
    name: Out Team name
    email: team@email.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: /api/docs/assets/translate-logo.png
    altText: Translation app logo
  tags:
    - name: organization
      description: |
        Markdown description of the organization tag
    - name: project
      description: |
        Markdown description of the project tag
    - name: Translation
      description: |
        Markdown description of the translation tag
  x-tagGroups:
    - name: Group 1
      tags:
        - Translation

paths:
  /api/translations/{projectName}:
    get:
      summary: Project translations
      description: |
        This endpoint allows you to get all the translations for a given Project.<br>
        You can also filter by specifying only the languages that you want.
      operationId: getSomething
      parameters:
        - $ref: "#/components/parameters/ProjectNameParam"
        - $ref: "#/components/parameters/GetProjectTranslationsLanguagesParam"
      responses:
        200:
          $ref: "#/components/responses/ProjectTranslationsGetResponse"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
      tags:
        - Translation

components:
  parameters:
    ProjectNameParam:
      name: projectName
      description: The name of the project.
      in: path
      required: true
      schema:
        type: string
      example:
        - traduction-project-1
    GetProjectTranslationsLanguagesParam:
      name: languages
      description: A list of Language codes
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      example: |
        For English and French, use [ en, fr ] - Or for  Portugese, German and Spanish, use [ pt, de, es ]
  responses:
    ProjectTranslationsGetResponse:
      description: Get translations for a given project
      content:
        application/json:
          schema:
            type: object
            required:
              - translations
              - total
            properties:
              translations:
                description: The list of translations
                type: array
                items:
                  $ref: "#/components/schemas/TranslationKeyDTO"
              total:
                description: The total amount of translations
                type: integer
          examples:
            Successful response:
              value:
                translations:
                  - key: home
                    languages:
                      - code: en
                        text: home
                      - code: pt
                        text: casa
                  - key: contact
                    languages:
                      - code: en
                        tect: contact
                      - code: pt
                        tect: contato
                  - key: about us
                    languages:
                      - code: en
                        tect: about us
                      - code: pt
                        tect: sobre nós
                total: 3
    BadRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
      description: BadRequest. Returned when the payload is invalid.
    NotFound:
      description: Returned when the requested ressource was not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFoundError"
    Conflict:
      description: Conflict. Returned when resource cannot be created because of business rules violation.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    TranslationKeyDTO:
      type: object
      required:
        - key
        - languages
      properties:
        key:
          type: string
          maxLength: 20
          minLength: 1
        languages:
          type: array
          items:
            $ref: "#/components/schemas/TranslationDTO"
    TranslationDTO:
      type: object
      required:
        - code
        - text
      properties:
        code:
          type: string
        text:
          type: string
    Error:
      description: Standard Error response.
      type: object
      required:
        - error_type
        - name
        - message
      properties:
        error_type:
          type: string
#          description: "example: `UNAUTHORIZED`."
        name:
          type: string
          description: Error name.
        message:
          type: string
          description: The detailed reason of the error.
    NotFoundError:
      description: Ressource not found Error response.
      allOf:
        - $ref: "#/components/schemas/Error"
        - type: object
          required:
             - error_type
          properties:
            error_type:
              type: string
              description: "example `The translations not found for this project`"
#  securitySchemes:
